### ISSUE TITLE
User can search for weather - Feature #1

### ISSUE THREAD

**Issue by lisale841** [lisale841/weather-meow#2]
## ⚙️ Feature

- User has the capability to search for current weather.

## 📐 Functionality
- User can search for weather based on city and state.

## 🖼️ Wireframes
<img width="411" alt="Screen Shot 2022-10-20 at 12 57 00 PM" src="https://user-images.githubusercontent.com/93673754/197046687-11889f95-97fe-4e14-94a1-4e81acb44eaf.png">

## ✅ Task List

- [x] Design Header
- [x] Create Homepage for application
- [x]  add input boxes
- [x]  add submit btn
